import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { FaCheckCircle, FaEdit, FaKey, FaPlus, FaTimes, FaTrash, FaUserShield } from 'react-icons/fa';
import { toast } from 'react-toastify';
import adminApi from '../services/adminApi';
import '../styles/SubAdminManagement.css';

const RESOURCE_LABELS = { dashboard: 'Dashboard', bookings: 'Bookings', categories: 'Categories', subcategories: 'Sub-Categories', services: 'Services', users: 'Users', offers: 'Offers & Coupons', technician_jobs: 'Technician Jobs', technician_verification: 'Technician Verification', blogs: 'Blogs', sub_admins: 'Sub-Admin Management', work_types: 'Work Types', service_types: 'Service Types' };
const ALL_RESOURCES = Object.keys(RESOURCE_LABELS);
const ROLE_DEFINITIONS = {
    admin: { label: 'Admin', description: 'Broad access to manage platform operations, users, services, and reports.', permissions: ALL_RESOURCES.map(resource => `${resource}:both`) },
    operations_dispatch: { label: 'Operations / Dispatch', description: 'Technician and job operations, assignment, monitoring, exceptions.', permissions: ['technician_jobs:both', 'dashboard:read', 'users:read'] },
    support_agents: { label: 'Support / Agents', description: 'Customer tickets, internal chats, and the support knowledge base.', permissions: ['users:both', 'bookings:both', 'dashboard:read'] },
    read_only_analyst: { label: 'Read-only / Analyst', description: 'View-only access across metrics, job lists, and system reports.', permissions: ['dashboard:read', 'bookings:read', 'users:read', 'technician_jobs:read', 'technician_verification:read'] }
};
const ROLE_CARDS = [{ key: 'super', label: 'Super Admin', description: 'Full access to every module, including admin users and configuration.' }, ...Object.entries(ROLE_DEFINITIONS).map(([key, role]) => ({ key, ...role }))];
const ACCESS_OPTIONS = [{ value: 'read', label: 'Read Only' }, { value: 'write', label: 'Write Only' }, { value: 'both', label: 'Read & Write' }];
const EMPTY_FORM = { name: '', email: '', password: '', role: 'read_only_analyst', permissions: [] };

const roleLabel = role => role === 'super' ? 'Super Admin' : role === 'verification' ? 'Admin' : ROLE_DEFINITIONS[role]?.label || 'Read-only / Analyst';
const rolePermissions = role => (ROLE_DEFINITIONS[role]?.permissions || []).map(value => { const [resource, access] = value.split(':'); return { resource, access }; });

function PermissionRow({ resource, perm, onChange, onRemove }) {
    return <div className="sam-permission-row"><span>{RESOURCE_LABELS[resource] || resource}</span><select value={perm} onChange={event => onChange(resource, event.target.value)}>{ACCESS_OPTIONS.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select><button type="button" aria-label={`Remove ${resource}`} onClick={() => onRemove(resource)}><FaTimes /></button></div>;
}

function AdminModal({ modal, form, setForm, resources, saving, onClose, onSubmit }) {
    const permissionMap = Object.fromEntries(form.permissions.map(permission => [permission.resource, permission.access]));
    const unusedResources = resources.filter(resource => !permissionMap[resource]);
    const changeRole = role => setForm(previous => ({ ...previous, role, permissions: rolePermissions(role) }));
    const addResource = resource => setForm(previous => ({ ...previous, permissions: [...previous.permissions, { resource, access: 'read' }] }));
    const changeAccess = (resource, access) => setForm(previous => ({ ...previous, permissions: previous.permissions.map(permission => permission.resource === resource ? { ...permission, access } : permission) }));
    const removeResource = resource => setForm(previous => ({ ...previous, permissions: previous.permissions.filter(permission => permission.resource !== resource) }));
    return <div className="sam-modal-backdrop"><div className="sam-modal" role="dialog" aria-modal="true"><div className="sam-modal-header"><div><span className="sam-eyebrow">{modal === 'create' ? 'New access profile' : 'Access profile'}</span><h2>{modal === 'create' ? 'Add admin' : 'Edit admin'}</h2></div><button className="sam-close" onClick={onClose} aria-label="Close"><FaTimes /></button></div><form onSubmit={onSubmit}><div className="sam-modal-body"><label className="sam-field"><span>Name</span><input required value={form.name} onChange={event => setForm(previous => ({ ...previous, name: event.target.value }))} placeholder="Full name" /></label><label className="sam-field"><span>Email</span><input required type="email" disabled={modal === 'edit'} value={form.email} onChange={event => setForm(previous => ({ ...previous, email: event.target.value }))} placeholder="admin@example.com" /></label><label className="sam-field"><span>Password {modal === 'edit' && <small>(leave blank to keep current)</small>}</span><input required={modal === 'create'} type="password" value={form.password} onChange={event => setForm(previous => ({ ...previous, password: event.target.value }))} placeholder="Enter a secure password" /></label><div className="sam-role-picker"><span className="sam-section-label">Assigned role</span><div className="sam-role-options">{Object.entries(ROLE_DEFINITIONS).map(([key, role]) => <button type="button" key={key} className={form.role === key ? 'selected' : ''} onClick={() => changeRole(key)}><strong>{role.label}</strong><small>{role.description}</small></button>)}</div></div><div className="sam-permissions"><div className="sam-permissions-heading"><span className="sam-section-label">Permissions</span>{unusedResources.length > 0 && <select aria-label="Add resource" value="" onChange={event => event.target.value && addResource(event.target.value)}><option value="">+ Add resource</option>{unusedResources.map(resource => <option key={resource} value={resource}>{RESOURCE_LABELS[resource] || resource}</option>)}</select>}</div>{form.permissions.length === 0 ? <p className="sam-muted">No permissions assigned.</p> : form.permissions.map(permission => <PermissionRow key={permission.resource} resource={permission.resource} perm={permission.access} onChange={changeAccess} onRemove={removeResource} />)}</div></div><div className="sam-modal-footer"><button type="button" className="sam-secondary" onClick={onClose}>Cancel</button><button className="sam-primary" disabled={saving}>{saving ? 'Saving...' : modal === 'create' ? 'Create admin' : 'Save changes'}</button></div></form></div></div>;
}

export default function SubAdminManagement() {
    const [subAdmins, setSubAdmins] = useState([]); const [resources, setResources] = useState([]); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(null); const [editing, setEditing] = useState(null); const [form, setForm] = useState(EMPTY_FORM); const [saving, setSaving] = useState(false);
    const load = useCallback(async () => { try { const [adminsResponse, resourcesResponse] = await Promise.all([adminApi.getSubAdmins(), adminApi.getResources()]); const adminsData = adminsResponse.data || adminsResponse; const resourcesData = resourcesResponse.data || resourcesResponse; setSubAdmins(adminsData.admins || []); setResources(resourcesData.resources || []); } catch { toast.error('Failed to load admins and roles.'); } finally { setLoading(false); } }, []);
    useEffect(() => { load(); }, [load]);
    const openCreate = () => { setForm({ ...EMPTY_FORM, permissions: rolePermissions(EMPTY_FORM.role) }); setEditing(null); setModal('create'); };
    const openEdit = admin => { const role = admin.role === 'verification' ? 'admin' : admin.role || 'read_only_analyst'; setEditing(admin); setForm({ name: admin.name, email: admin.email, password: '', role, permissions: admin.permissions || rolePermissions(role) }); setModal('edit'); };
    const closeModal = () => { setModal(null); setEditing(null); setForm(EMPTY_FORM); };
    const handleSubmit = async event => { event.preventDefault(); setSaving(true); try { const payload = { name: form.name, role: form.role, permissions: form.permissions }; if (modal === 'create') { await adminApi.createSubAdmin({ ...payload, email: form.email, password: form.password }); toast.success('Admin created.'); } else { if (form.password) payload.password = form.password; await adminApi.updateSubAdmin(editing._id, payload); toast.success('Admin updated.'); } closeModal(); await load(); } catch (error) { toast.error(error.response?.data?.message || 'Operation failed.'); } finally { setSaving(false); } };
    const toggleActive = async admin => { try { await adminApi.updateSubAdmin(admin._id, { isActive: !admin.isActive }); toast.success(`Admin ${admin.isActive ? 'deactivated' : 'activated'}.`); load(); } catch (error) { toast.error(error.response?.data?.message || 'Failed to update status.'); } };
    const handleDelete = async id => { if (!window.confirm('Delete this admin?')) return; try { await adminApi.deleteSubAdmin(id); toast.success('Admin deleted.'); load(); } catch (error) { toast.error(error.response?.data?.message || 'Delete failed.'); } };
    const counts = useMemo(() => Object.fromEntries(Object.keys(ROLE_DEFINITIONS).map(role => [role, subAdmins.filter(admin => admin.role === role).length])), [subAdmins]);
    if (loading) return <div className="sam-loading"><div className="spinner-border spinner-border-sm text-warning" /> Loading...</div>;
    return <div className="sam-page"><div className="sam-breadcrumb">People &amp; Support <span>/</span> <b>Configuration</b></div><header className="sam-header"><div><h1>Manage Admins and Roles</h1><p>Manage who can access the admin panel and what they can do</p></div><button className="sam-add-button" onClick={openCreate}><FaPlus /> Add admin</button></header><section className="sam-role-cards" aria-label="Admin roles">{ROLE_CARDS.map(role => <article className={`sam-role-card sam-role-${role.key}`} key={role.key}><h2>{role.label}</h2><p>{role.description}</p>{role.key !== 'super' && <span>{counts[role.key] || 0} assigned</span>}</article>)}</section>{subAdmins.length === 0 ? <div className="sam-empty"><FaUserShield /><strong>No admins yet</strong><span>Create an admin to delegate access.</span></div> : <div className="sam-table-wrap"><table className="sam-table"><thead><tr>{['Name', 'Email', 'Role', 'Status', 'Last Active', 'Created', 'Actions'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{subAdmins.map(admin => <tr key={admin._id}><td><div className="sam-name"><span>{(admin.name || '?').split(/\s+/).map(word => word[0]).slice(0, 2).join('').toUpperCase()}</span><strong>{admin.name}</strong></div></td><td className="sam-email">{admin.email}</td><td><span className="sam-role-pill">{admin.isSuperAdmin ? 'Super Admin' : roleLabel(admin.role)}</span></td><td><button className={`sam-status ${admin.isActive ? 'active' : 'inactive'}`} onClick={() => toggleActive(admin)}>{admin.isActive ? <><FaCheckCircle /> Active</> : 'Inactive'}</button></td><td className="sam-muted">{admin.lastActive ? new Date(admin.lastActive).toLocaleString() : 'Not available'}</td><td className="sam-muted">{admin.createdAt ? new Date(admin.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '-'}</td><td><div className="sam-actions"><button title="Edit admin" onClick={() => openEdit(admin)}><FaEdit /></button><button title="Delete admin" onClick={() => handleDelete(admin._id)}><FaTrash /></button></div></td></tr>)}</tbody></table></div>}{modal && <AdminModal modal={modal} form={form} setForm={setForm} resources={resources} saving={saving} onClose={closeModal} onSubmit={handleSubmit} />}</div>;
}