const router = require('express').Router();
const multer = require('multer');
const Admin = require('../models/Admin');
const controller = require('../controllers/offerController');
const { protect, restrictTo, checkPermission } = require('../middleware/auth');
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 2 * 1024 * 1024 }, fileFilter: (req, file, cb) => { if (['image/jpeg', 'image/png', 'image/webp'].includes(file.mimetype)) return cb(null, true); const error = new Error('Choose a JPG, PNG or WebP image.'); error.statusCode = 400; cb(error); } }).single('image');
router.use(protect);
router.get('/', restrictTo('user'), controller.available);
router.post('/validate', restrictTo('user'), controller.validate);
router.use('/admin', (req, res, next) => req.user instanceof Admin && req.user.isActive ? next() : res.status(403).json({ success: false, message: 'Active admin account required.' }));
router.get('/admin', checkPermission('offers', 'read'), controller.list);
router.get('/admin/options', checkPermission('offers', 'read'), controller.options);
router.post('/admin/image', checkPermission('offers', 'write'), (req, res, next) => upload(req, res, err => { if (err) { err.statusCode = 400; if (err.code === 'LIMIT_FILE_SIZE') err.message = 'Choose an image up to 2 MB.'; return next(err); } next(); }), controller.upload);
router.post('/admin', checkPermission('offers', 'write'), controller.save);
router.put('/admin/:id', checkPermission('offers', 'write'), controller.save);
router.patch('/admin/:id/status', checkPermission('offers', 'write'), controller.status);
router.patch('/admin/:id/image', checkPermission('offers', 'write'), controller.image);
router.get('/admin/:id/redemptions', checkPermission('offers', 'read'), controller.redemptions);
module.exports = router;
