import React, { useEffect, useState } from 'react';
import { FiArrowLeft, FiEdit2, FiSlash, FiPhone, FiMail, FiMoreVertical, FiMapPin, FiCalendar, FiCheck, FiInfo, FiX, FiDownload } from 'react-icons/fi';
import { FaStar, FaCrown } from 'react-icons/fa';
import { toast } from 'react-toastify';
import adminApi from '../services/adminApi';
import '../styles/CustomerDetails.css';

const date = value => value && !Number.isNaN(new Date(value).getTime()) ? new Date(value).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
const time = value => value && !Number.isNaN(new Date(value).getTime()) ? new Date(value).toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' }) : '';
const money = value => `₹${Number(value || 0).toLocaleString('en-IN')}`;
const id = item => item?.bookingId || item?.customerId || item?._id || '—';
const service = booking => booking?.services?.map(s => s.service?.name || s.variantName || 'Service').join(', ') || 'Service booking';
const addressText = address => [address.addressLine, address.city, address.state, address.zipcode].filter(Boolean).join(', ');
const ongoing = status => ['Pending', 'Confirmed', 'Assigned', 'On the Way', 'In Progress', 'Checkout', 'Ongoing'].includes(status);
const isActivePlan = plan => plan?.status === 'active' && (!plan.expiresAt || new Date(plan.expiresAt) > new Date());
function Badge({ children }) {
    const value = String(children || 'Unknown');
    const color = ['active', 'paid', 'completed', 'resolved'].includes(value.toLowerCase()) ? 'success' : ['ongoing', 'open', 'refunded', 'home'].includes(value.toLowerCase()) ? 'purple' : ['pending', 'high'].includes(value.toLowerCase()) ? 'warning' : ['failed', 'blocked'].includes(value.toLowerCase()) ? 'danger' : 'muted';
    return <span className={`cd-badge ${color}`}>{value}</span>;
}
function Card({ title, action, children, className = '' }) { return <section className={`cd-card ${className}`}><div className="cd-card-title"><h3>{title}</h3>{action}</div>{children}</section>; }
function Rows({ values }) { return <dl className="cd-values">{values.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || 'Not specified'}</dd></div>)}</dl>; }
function Empty({ children }) { return <p className="cd-empty">{children}</p>; }
function Avatar({ user }) {
    const photo = user.profileImage?.url || user.photoUrl || user.profilePhoto || user.avatar;
    const [failedPhoto, setFailedPhoto] = useState(null);
    return <span className="cd-avatar">{photo && failedPhoto !== photo ? <img src={photo} alt={user.name} onError={() => setFailedPhoto(photo)} /> : (user.name || 'Customer').split(' ').map(n => n[0]).slice(0, 2).join('')}</span>;
}

export default function CustomerDetails({ user, tab, setTab, overview, onEdit, onStatus, saving, onBack, onExport, onRefresh }) {
    const [bookingFilter, setBookingFilter] = useState('All');
    const [from, setFrom] = useState('');
    const [to, setTo] = useState('');
    const [dialog, setDialog] = useState(null);
    const [addressForm, setAddressForm] = useState({});
    const [addressSaving, setAddressSaving] = useState(false);
    useEffect(() => { setBookingFilter('All'); setFrom(''); setTo(''); setDialog(null); }, [user._id]);
    const bookings = user.bookings || [];
    const reviews = user.reviews || [];
    const tickets = user.supportTickets || [];
    const addresses = user.addresses?.length ? user.addresses : user.address ? [{ label: 'Home', addressLine: user.address }] : [];
    const purchases = user.planPurchases || [];
    const plan = purchases.find(isActivePlan) || purchases[0];
    const blocked = ['inactive', 'blocked', 'suspended'].includes(user.accountStatus);
    const average = reviews.length ? reviews.reduce((sum, r) => sum + Number(r.rating), 0) / reviews.length : user.rating;
    const counts = { Addresses: addresses.length, Bookings: bookings.length, Payments: bookings.length, Support: tickets.length, Reviews: reviews.length };
    const filtered = bookings.filter(b => (bookingFilter === 'All' || (bookingFilter === 'Ongoing' ? ongoing(b.status) : b.status === bookingFilter)) && (!from || new Date(b.serviceDate) >= new Date(`${from}T00:00:00`)) && (!to || new Date(b.serviceDate) <= new Date(`${to}T23:59:59.999`)));
    const events = [
        { title: 'Customer registered', at: user.createdAt, Icon: FiCheck, color: 'green' },
        ...bookings.map(b => ({ title: `Booking created — ${service(b)} (${id(b)})`, at: b.createdAt, Icon: FiCalendar, color: 'blue' })),
        ...reviews.map(r => ({ title: `Review submitted — ${r.rating}★ for ${r.service?.name || 'Service'}`, at: r.createdAt, Icon: FaStar, color: 'orange' })),
        ...purchases.map(p => ({ title: `Membership purchased — ${p.planName}`, at: p.paidAt || p.createdAt, Icon: FaCrown, color: 'green' })),
        ...tickets.map(t => ({ title: `Support ticket created — ${t.subject}`, at: t.createdAt, Icon: FiInfo, color: 'orange' }))
    ].filter(e => e.at).sort((a, b) => new Date(b.at) - new Date(a.at));
    const editAddress = (address, index) => { setAddressForm({ ...address }); setDialog({ type: 'address', index }); };
    const saveAddress = async event => {
        event.preventDefault(); setAddressSaving(true);
        try {
            await adminApi.updateCustomer(user._id, { addresses: addresses.map((a, i) => i === dialog.index ? addressForm : a) });
            toast.success('Address updated'); setDialog(null); onRefresh();
        } catch (error) { toast.error(error.response?.data?.message || 'Could not update address'); }
        finally { setAddressSaving(false); }
    };
    const bookingTable = <div className="cd-table-wrap"><table className="cd-table"><thead><tr>{['Booking ID', 'Service', 'Date & Time', 'Technician', 'Amount', 'Payment', 'Status', ''].map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{filtered.map(b => <tr key={b._id}><td><strong>{id(b)}</strong></td><td><strong>{service(b)}</strong><small>{b.services?.[0]?.variantName || ''}</small></td><td>{date(b.serviceDate)}<small>{time(b.serviceDate)}</small></td><td>{b.assignedTechnician?.name || 'Unassigned'}</td><td><strong>{money(b.totalAmount)}</strong></td><td><Badge>{b.paymentStatus}</Badge></td><td><Badge>{ongoing(b.status) ? 'Ongoing' : b.status}</Badge></td><td><button className="cd-button" onClick={() => setDialog({ type: 'booking', booking: b })}>View Booking</button></td></tr>)}{!filtered.length && <tr><td colSpan={8}><Empty>No bookings match these filters.</Empty></td></tr>}</tbody></table></div>;
    return <div className="customer-details">
        <button className="cd-back" onClick={onBack}><FiArrowLeft /> Back to customers</button>
        <header className="cd-profile"><Avatar user={user} /><div className="cd-profile-copy"><h2>{user.name} <Badge>{blocked ? 'Blocked' : 'Active'}</Badge></h2><small className="cd-customer-id">{id(user)}</small><div className="cd-contact"><span><FiPhone /> {user.phone}</span><span><FiMail /> {user.email}</span></div><div className="cd-meta"><span>Registered {date(user.createdAt)}</span><span>Last booking {date(bookings[0]?.serviceDate)}</span>{average > 0 && <span className="cd-header-rating"><FaStar /> {Number(average).toFixed(1)}</span>}</div></div><div className="cd-profile-actions"><button className="cd-button" onClick={() => onEdit(user)}><FiEdit2 /> Edit Customer</button><button className="cd-button cd-block" disabled={saving} onClick={() => onStatus(user)}><FiSlash /> {blocked ? 'Unblock' : 'Block'} Customer</button><details className="cd-more"><summary aria-label="More customer actions"><FiMoreVertical /></summary><button onClick={onExport}><FiDownload /> Export customers</button></details></div></header>
        <nav className="cd-tabs" aria-label="Customer details">{['Overview', 'Personal Info', 'Addresses', 'Bookings', 'Payments', 'Support', 'Reviews', 'Membership', 'Activity'].map(t => <button key={t} aria-label={t} aria-current={tab === t ? 'page' : undefined} className={tab === t ? 'active' : ''} onClick={() => setTab(t)}>{t}{counts[t] !== undefined && <span>{counts[t]}</span>}</button>)}</nav>
        <div className="cd-content">
            {tab === 'Overview' && overview}
            {tab === 'Personal Info' && <div className="cd-personal-grid"><Card title="Basic Information" action={<button className="cd-button cd-small" onClick={() => onEdit(user)}><FiEdit2 /> Edit</button>}><div className="cd-mini-profile"><Avatar user={user} /><div><strong>{user.name}</strong><small>{id(user)}</small></div></div><Rows values={[[ 'Mobile', user.phone], ['Email', user.email], ['Date of birth', date(user.dateOfBirth)]]} /></Card><Card title="Preferences"><Rows values={[[ 'Language', user.language], ['Notifications', user.notificationPreferences?.join(', ')], ['Communication preference', user.communicationPreference]]} /></Card><Card title="Emergency & Safety"><Rows values={[[ 'Emergency contact', user.emergencyContact?.name ? <>{user.emergencyContact.name}{user.emergencyContact.relationship && <span className="cd-subtle"> ({user.emergencyContact.relationship})</span>}<br />{user.emergencyContact.phone}</> : user.alternateContact], ['Safety preferences', user.safetyPreferences]]} /></Card></div>}
            {tab === 'Addresses' && <div className="cd-address-grid">{addresses.map((a, i) => <section className="cd-card cd-address-card" key={a._id || i}><Badge>{a.label || 'Home'}</Badge><p>{addressText(a)}</p><div className="cd-location"><FiMapPin />{a.coordinates?.lat != null && a.coordinates?.lng != null ? `Location saved · ${a.coordinates.lat}°, ${a.coordinates.lng}°` : 'Coordinates not saved'}</div><div className="cd-address-actions"><a className="cd-button" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(a.coordinates?.lat != null && a.coordinates?.lng != null ? `${a.coordinates.lat},${a.coordinates.lng}` : addressText(a))}`} target="_blank" rel="noreferrer"><FiMapPin /> View on Map</a><button className="cd-text-button" onClick={() => editAddress(a, i)}><FiEdit2 /> Edit</button>{a.isDefault && <Badge>Default</Badge>}</div></section>)}{!addresses.length && <Card title="Saved Addresses"><Empty>No saved addresses.</Empty></Card>}</div>}
            {tab === 'Bookings' && <><div className="cd-booking-toolbar"><div className="cd-filter-pills">{['All', 'Ongoing', 'Completed', 'Failed', 'Cancelled'].map(f => <button key={f} className={bookingFilter === f ? 'active' : ''} onClick={() => setBookingFilter(f)}>{f}</button>)}</div><div className="cd-date-range"><label>From <input type="date" aria-label="Bookings from date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>To <input type="date" aria-label="Bookings to date" min={from} value={to} onChange={e => setTo(e.target.value)} /></label></div></div>{bookingTable}</>}
            {tab === 'Payments' && <><div className="cd-table-wrap"><table className="cd-table"><thead><tr>{['Transaction ID', 'Booking ID', 'Amount', 'Payment Method', 'Status', 'Date', ''].map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{bookings.map(b => <tr key={b._id}><td><strong>{b.paymentDetails?.transactionId || b.paymentDetails?.paymentId || '—'}</strong></td><td><button className="cd-inline-link" onClick={() => setDialog({ type: 'booking', booking: b })}>{id(b)}</button></td><td><strong>{money(b.totalAmount)}</strong></td><td>{b.paymentDetails?.provider || 'Not recorded'}</td><td><Badge>{b.paymentStatus}</Badge></td><td>{date(b.paymentDetails?.paidAt || b.createdAt)}</td><td><button className="cd-button" onClick={() => setDialog({ type: 'payment', booking: b })}>View Transaction</button></td></tr>)}{!bookings.length && <tr><td colSpan={7}><Empty>No payments available.</Empty></td></tr>}</tbody></table></div><p className="cd-note"><FiInfo /> Full card and bank details are never displayed.</p></>}
            {tab === 'Membership' && <>{plan ? <><div className={`cd-membership-banner ${isActivePlan(plan) ? '' : 'inactive'}`}><FaCrown /><span><strong>{plan.planName}</strong> — membership {isActivePlan(plan) ? 'active' : plan.status}.</span></div><div className="cd-membership-grid"><Card title="Membership Details" action={<span className="cd-id-tag">{plan._id}</span>}><Rows values={[[ 'Plan', plan.planName], ['Billing cycle', plan.durationMonths === 12 ? 'Annual' : `${plan.durationMonths || '—'} months`], ['Amount paid', money(plan.price)], ['Purchase date', date(plan.paidAt || plan.createdAt)], ['Valid until', date(plan.expiresAt)], ['Status', <Badge>{isActivePlan(plan) ? 'Active' : plan.status === 'active' ? 'Expired' : plan.status}</Badge>], ['Payment status', <Badge>{plan.paidAt ? 'Paid' : 'Pending'}</Badge>]]} /></Card><Card title="Benefits Used">{plan.benefitUsage?.length ? plan.benefitUsage.map(b => <div className="cd-benefit" key={b.name}><div>{b.name}<strong>{b.used}/{b.limit}</strong></div><progress value={b.used} max={b.limit || 1} /></div>) : <Empty>Benefit usage has not been recorded.</Empty>}{plan.features?.length > 0 && <ul className="cd-features">{plan.features.map(f => <li key={f}><FiCheck />{f}</li>)}</ul>}<a href="/plans" className="cd-button cd-primary"><FaCrown /> View Membership</a></Card></div></> : <Card title="Membership"><Empty>No membership purchased.</Empty></Card>}</>}
            {tab === 'Reviews' && <><section className="cd-card cd-review-summary"><div className="cd-review-average"><strong>{average ? Number(average).toFixed(1) : '—'} <FaStar /></strong><p>{reviews.length} reviews · average rating</p></div><div className="cd-distribution">{[5, 4, 3, 2, 1].map(stars => { const count = reviews.filter(r => Number(r.rating) === stars).length; return <div key={stars}><span>{stars}★</span><progress value={count} max={reviews.length || 1} /><small>{count}</small></div>; })}</div></section><div className="cd-review-list">{reviews.map(r => { const b = bookings.find(b => b._id === (r.booking?._id || r.booking)); return <section className="cd-card cd-review" key={r._id}><div className="cd-review-top"><span className="cd-stars">{[1, 2, 3, 4, 5].map(n => <FaStar key={n} className={n <= r.rating ? '' : 'unfilled'} />)}</span><small>{date(r.createdAt)}</small></div><p>{r.review || 'No written review.'}</p><div className="cd-review-bottom"><span className="cd-id-tag">{b ? id(b) : r.booking?._id || r.booking}</span><span>{r.service?.name || (b && service(b))}{b?.assignedTechnician?.name && ` · ${b.assignedTechnician.name}`}</span>{b && <button className="cd-button" onClick={() => setDialog({ type: 'booking', booking: b })}>View Booking</button>}</div></section>; })}{!reviews.length && <Card title="Reviews"><Empty>No reviews submitted.</Empty></Card>}</div></>}
            {tab === 'Support' && <div className="cd-table-wrap"><table className="cd-table"><thead><tr>{['Ticket ID', 'Subject', 'Category', 'Created', 'Priority', 'Status', 'Assigned To', ''].map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{tickets.map(t => <tr key={t._id}><td><strong>{t.ticketId || t._id}</strong></td><td><strong>{t.subject}</strong></td><td>{t.category}</td><td>{date(t.createdAt)}</td><td><Badge>{t.priority}</Badge></td><td><Badge>{t.status}</Badge></td><td>{t.assignedTo?.name || 'Unassigned'}</td><td><button className="cd-button" onClick={() => setDialog({ type: 'ticket', ticket: t })}>View Ticket</button></td></tr>)}{!tickets.length && <tr><td colSpan={8}><Empty>No support tickets available.</Empty></td></tr>}</tbody></table></div>}
            {tab === 'Activity' && <section className="cd-card cd-timeline">{events.map((e, i) => <div className="cd-event" key={i}><span className={`cd-event-icon ${e.color}`}><e.Icon /></span><div><strong>{e.title}</strong><small>{date(e.at)}{time(e.at) && `, ${time(e.at)}`}</small></div></div>)}{!events.length && <Empty>No recorded activity.</Empty>}</section>}
        </div>
        {dialog && <div className="cd-dialog-backdrop" onClick={() => !addressSaving && setDialog(null)}><section className="cd-dialog cd-card" role="dialog" aria-modal="true" aria-label={dialog.type === 'address' ? 'Edit address' : dialog.type === 'payment' ? 'Transaction details' : dialog.type === 'ticket' ? 'Ticket details' : 'Booking details'} onClick={e => e.stopPropagation()}><div className="cd-card-title"><h3>{dialog.type === 'address' ? 'Edit Address' : dialog.type === 'payment' ? 'Transaction Details' : dialog.type === 'ticket' ? 'Ticket Details' : 'Booking Details'}</h3><button className="cd-text-button" aria-label="Close details" disabled={addressSaving} onClick={() => setDialog(null)}><FiX /></button></div>{dialog.type === 'address' ? <form onSubmit={saveAddress}>{[['label', 'Label'], ['addressLine', 'Street address'], ['city', 'City'], ['state', 'State'], ['zipcode', 'Postal code']].map(([key, label]) => <label className="cd-form-label" key={key}>{label}<input required={key === 'addressLine'} value={addressForm[key] || ''} onChange={e => setAddressForm(a => ({ ...a, [key]: e.target.value }))} /></label>)}<button className="cd-button cd-primary" disabled={addressSaving}>{addressSaving ? 'Saving...' : 'Save Address'}</button></form> : dialog.type === 'ticket' ? <Rows values={[[ 'Ticket ID', dialog.ticket.ticketId || dialog.ticket._id], ['Subject', dialog.ticket.subject], ['Status', dialog.ticket.status], ['Description', dialog.ticket.description]]} /> : <Rows values={dialog.type === 'payment' ? [[ 'Transaction ID', dialog.booking.paymentDetails?.transactionId || dialog.booking.paymentDetails?.paymentId || 'Not recorded'], ['Booking ID', id(dialog.booking)], ['Amount', money(dialog.booking.totalAmount)], ['Provider', dialog.booking.paymentDetails?.provider], ['Payment status', <Badge>{dialog.booking.paymentStatus}</Badge>]] : [[ 'Booking ID', id(dialog.booking)], ['Service', service(dialog.booking)], ['Date & time', `${date(dialog.booking.serviceDate)}, ${time(dialog.booking.serviceDate)}`], ['Technician', dialog.booking.assignedTechnician?.name || 'Unassigned'], ['Address', typeof dialog.booking.address === 'string' ? dialog.booking.address : addressText(dialog.booking.address || {})], ['Amount', money(dialog.booking.totalAmount)], ['Status', <Badge>{dialog.booking.status}</Badge>]]} />}</section></div>}
    </div>;
}
