import React, { useState } from 'react';
import LocationPicker from './LocationPicker';
import ReactQuill from 'react-quill-new';
import 'react-quill-new/dist/quill.snow.css';
import { FaTools, FaPlus, FaTimes, FaRupeeSign, FaCalendarAlt } from 'react-icons/fa';

// ─── TaskBuilder ───────────────────────────────────────────────────────────────
const TASK_GROUPS = ['Prep', 'On Site', 'Post'];
const TaskBuilder = ({ tasks, onChange }) => {
  const [newTitle, setNewTitle] = useState('');
  const [newGroup, setNewGroup] = useState('Prep');
  const addTask = () => { const t = newTitle.trim(); if (!t) return; onChange([...tasks, { title: t, group: newGroup, order: tasks.length, isDone: false }]); setNewTitle(''); };
  const removeTask = (idx) => onChange(tasks.filter((_, i) => i !== idx));
  const updateTask = (idx, field, value) => onChange(tasks.map((task, i) => i === idx ? { ...task, [field]: value } : task));
  return (
    <div className="tj-task-builder">
      <label className="tj-label"><FaTools className="me-1" style={{ color: '#A5732F' }} /> Tasks for Technician</label>
      {TASK_GROUPS.map(g => { const gTasks = tasks.filter(t => t.group === g); if (!gTasks.length) return null; return (<div key={g} className="tj-task-group"><div className="tj-task-group-label">{g}</div>{gTasks.map(t => { const gi = tasks.indexOf(t); const requiresEvidence = t.requiresNote || t.requiresImage || t.requiresSignature; return (<div key={gi} className="tj-task-row" style={{ alignItems: 'flex-start' }}><span className="tj-task-circle" style={{ marginTop: 4 }} /><div style={{ flex: 1 }}><span className="tj-task-title">{t.title}</span><div className="d-flex gap-3 flex-wrap mt-1"><label className="small text-muted"><input type="checkbox" className="me-1" checked={Boolean(t.requiresNote)} onChange={(e) => updateTask(gi, 'requiresNote', e.target.checked)} />Require note</label><label className="small text-muted"><input type="checkbox" className="me-1" checked={Boolean(t.requiresImage)} onChange={(e) => updateTask(gi, 'requiresImage', e.target.checked)} />Require image</label><label className="small text-muted"><input type="checkbox" className="me-1" checked={Boolean(t.requiresSignature)} onChange={(e) => updateTask(gi, 'requiresSignature', e.target.checked)} />Require signature</label></div>{requiresEvidence && <input className="form-control tj-input mt-2" value={t.requirementReason || ''} onChange={(e) => updateTask(gi, 'requirementReason', e.target.value)} placeholder="Why is this evidence required?" required />}</div><button type="button" className="tj-task-remove" onClick={() => removeTask(gi)}><FaTimes /></button></div>); })}</div>); })}
      <div className="tj-task-add-row">
        <select className="tj-task-group-select" value={newGroup} onChange={(e) => setNewGroup(e.target.value)}>{TASK_GROUPS.map(g => <option key={g}>{g}</option>)}</select>
        <input className="tj-task-input" placeholder="Task title…" value={newTitle} onChange={(e) => setNewTitle(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); addTask(); } }} />
        <button type="button" className="tj-task-add-btn" onClick={addTask} disabled={!newTitle.trim()}><FaPlus /></button>
      </div>
    </div>
  );
};

// ─── JobForm ───────────────────────────────────────────────────────────────────
const JobForm = ({ form, setForm, onSubmit, onCancel, isEditing, saving, workTypes, serviceTypes, isTemplate = false }) => {
  const primarySubTypes = workTypes.find(w => w._id === form.workTypeId)?.subTypes?.filter(s => s.isActive) || [];
  const additionalSubTypes = workTypes.find(w => w._id === form.additionalWorkTypeId)?.subTypes?.filter(s => s.isActive) || [];
  return (
    <form onSubmit={onSubmit} className="row g-3">
      {isTemplate && <div className="col-12"><label className="tj-label" htmlFor="tj-template-name">Template Name <span className="text-danger">*</span></label><input id="tj-template-name" className="form-control tj-input" value={form.templateName || ''} onChange={e => setForm({ ...form, templateName: e.target.value })} required maxLength={120} placeholder="e.g. Standard AC installation" /><small className="text-muted">Save reusable job details. You can change them before posting a job.</small></div>}
      <div className="col-12"><label className="tj-label">Job Title <span className="text-danger">*</span></label><input className="form-control tj-input" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="e.g. AC Service Repair" required /></div>
      <div className="col-12">
        <div className="p-3 rounded-3 mb-1" style={{ background: 'rgba(165,115,47,0.05)', border: '1px solid rgba(165,115,47,0.15)' }}>
          <p className="tj-label mb-3" style={{ color: '#A5732F' }}><FaTools className="me-1" /> Work Type Information</p>
          <div className="row g-3">
            <div className="col-md-6"><label className="tj-label">Type of Work</label><select className="form-select tj-input" value={form.workTypeId} onChange={(e) => setForm({ ...form, workTypeId: e.target.value, workTypeSubId: '' })}><option value="">— Select work type —</option>{workTypes.filter(w => w.isActive).map(w => <option key={w._id} value={w._id}>{w.name}</option>)}</select></div>
            <div className="col-md-6"><label className="tj-label">Work Sub-Type</label><select className="form-select tj-input" value={form.workTypeSubId} onChange={(e) => setForm({ ...form, workTypeSubId: e.target.value })} disabled={!form.workTypeId}><option value="">— Select sub-type —</option>{primarySubTypes.map(s => <option key={s._id} value={s._id}>{s.name}</option>)}</select></div>
            <div className="col-md-6"><label className="tj-label">Additional Type of Work</label><select className="form-select tj-input" value={form.additionalWorkTypeId} onChange={(e) => setForm({ ...form, additionalWorkTypeId: e.target.value, additionalWorkTypeSubId: '' })}><option value="">— Select additional work type —</option>{workTypes.filter(w => w.isActive).map(w => <option key={w._id} value={w._id}>{w.name}</option>)}</select></div>
            <div className="col-md-6"><label className="tj-label">Additional Work Sub-Type</label><select className="form-select tj-input" value={form.additionalWorkTypeSubId} onChange={(e) => setForm({ ...form, additionalWorkTypeSubId: e.target.value })} disabled={!form.additionalWorkTypeId}><option value="">— Select sub-type —</option>{additionalSubTypes.map(s => <option key={s._id} value={s._id}>{s.name}</option>)}</select></div>
            <div className="col-md-6"><label className="tj-label">Service Type</label><select className="form-select tj-input" value={form.serviceTypeId} onChange={(e) => setForm({ ...form, serviceTypeId: e.target.value })}><option value="">— Select service type —</option>{serviceTypes.filter(s => s.isActive).map(s => <option key={s._id} value={s._id}>{s.name}</option>)}</select></div>
          </div>
        </div>
      </div>
      <div className="col-12">
        <div className="p-3 rounded-3" style={{ background: 'rgba(37,99,235,0.04)', border: '1px solid rgba(37,99,235,0.15)' }}>
          <p className="tj-label mb-3" style={{ color: '#2563eb' }}><FaRupeeSign className="me-1" /> Pay</p>
          <div className="d-flex gap-2 mb-3 flex-wrap">
            {[{ key: 'hourly', label: 'Hourly' },{ key: 'fixed', label: 'Fixed' },{ key: 'perDevice', label: 'Per Device' },{ key: 'blended', label: 'Blended' }].map(({ key, label }) => (
              <button key={key} type="button" onClick={() => setForm({ ...form, pay: { ...form.pay, type: key } })} style={{ padding: '6px 20px', borderRadius: 6, border: form.pay.type === key ? '2px solid #2563eb' : '1.5px solid #ced4da', background: form.pay.type === key ? '#fff' : 'transparent', fontWeight: form.pay.type === key ? 700 : 500, color: form.pay.type === key ? '#2563eb' : '#6c757d', cursor: 'pointer', fontSize: 14 }}>{label}</button>
            ))}
          </div>
          {form.pay.type === 'hourly' && <div className="row g-3"><div className="col-md-6"><label className="tj-label">Hourly Rate ($) <span className="text-danger">*</span></label><div className="input-group"><span className="input-group-text bg-light border-0">$</span><input className="form-control tj-input border-start-0" type="number" min="0" step="0.01" value={form.pay.hourlyRate} onChange={e => setForm({ ...form, pay: { ...form.pay, hourlyRate: e.target.value } })} placeholder="0" required /></div></div><div className="col-md-6"><label className="tj-label">Max Hours</label><input className="form-control tj-input" type="number" min="0" step="0.5" value={form.pay.maxHours} onChange={e => setForm({ ...form, pay: { ...form.pay, maxHours: e.target.value } })} placeholder="0" /><small className="text-muted">1 hour minimum</small></div><div className="col-md-6"><label className="tj-label">Approx. Hours <span className="text-muted small">— Optional</span></label><input className="form-control tj-input" type="text" value={form.pay.approxHours} onChange={e => setForm({ ...form, pay: { ...form.pay, approxHours: e.target.value } })} placeholder="e.g. 2–3 hours" /></div></div>}
          {form.pay.type === 'fixed' && <div className="row g-3"><div className="col-md-6"><label className="tj-label">Total Pay ($) <span className="text-danger">*</span></label><div className="input-group"><span className="input-group-text bg-light border-0">$</span><input className="form-control tj-input border-start-0" type="number" min="0" step="0.01" value={form.pay.fixedAmount} onChange={e => setForm({ ...form, pay: { ...form.pay, fixedAmount: e.target.value } })} placeholder="0" required /></div></div><div className="col-md-6"><label className="tj-label">Approx. Hours to Complete</label><input className="form-control tj-input" type="text" value={form.pay.approxHours} onChange={e => setForm({ ...form, pay: { ...form.pay, approxHours: e.target.value } })} placeholder="e.g. 2–3 hours" /></div></div>}
          {form.pay.type === 'perDevice' && <div className="row g-3"><div className="col-md-6"><label className="tj-label">Per Device Rate ($) <span className="text-danger">*</span></label><div className="input-group"><span className="input-group-text bg-light border-0">$</span><input className="form-control tj-input border-start-0" type="number" min="0" step="0.01" value={form.pay.perDeviceRate} onChange={e => setForm({ ...form, pay: { ...form.pay, perDeviceRate: e.target.value } })} placeholder="0" required /></div></div><div className="col-md-6"><label className="tj-label">Max Devices</label><input className="form-control tj-input" type="number" min="0" value={form.pay.maxDevices} onChange={e => setForm({ ...form, pay: { ...form.pay, maxDevices: e.target.value } })} placeholder="0" /></div></div>}
          {form.pay.type === 'blended' && <div className="row g-3"><div className="col-md-6"><label className="tj-label">Fixed Payment ($) <span className="text-danger">*</span></label><div className="input-group"><span className="input-group-text bg-light border-0">$</span><input className="form-control tj-input border-start-0" type="number" min="0" step="0.01" value={form.pay.blendedFixedAmount} onChange={e => setForm({ ...form, pay: { ...form.pay, blendedFixedAmount: e.target.value } })} placeholder="0" required /></div></div><div className="col-md-6"><label className="tj-label">Fixed Hours</label><input className="form-control tj-input" type="number" min="0" step="0.5" value={form.pay.blendedFixedHours} onChange={e => setForm({ ...form, pay: { ...form.pay, blendedFixedHours: e.target.value } })} placeholder="0" /></div><div className="col-md-6"><label className="tj-label">Additional Hour Rate ($)</label><div className="input-group"><span className="input-group-text bg-light border-0">$</span><input className="form-control tj-input border-start-0" type="number" min="0" step="0.01" value={form.pay.blendedHourlyRate} onChange={e => setForm({ ...form, pay: { ...form.pay, blendedHourlyRate: e.target.value } })} placeholder="0" /></div></div><div className="col-md-6"><label className="tj-label">Max Additional Hours</label><input className="form-control tj-input" type="number" min="0" step="0.5" value={form.pay.blendedMaxAddlHours} onChange={e => setForm({ ...form, pay: { ...form.pay, blendedMaxAddlHours: e.target.value } })} placeholder="0" /></div></div>}
        </div>
      </div>
      <div className="col-12"><label className="tj-label">Location <span className="text-danger">*</span></label><LocationPicker value={form.coordinates ? { address: form.location, ...form.coordinates } : null} onChange={({ address, lat, lng, city = '', state = '', zipCode = '' }) => setForm({ ...form, location: address, coordinates: { lat, lng }, city, state, zipCode })} /></div>
      <div className="col-md-4"><label className="tj-label">City</label><input className="form-control tj-input" type="text" placeholder="Auto-filled from map" value={form.city} onChange={e => setForm({ ...form, city: e.target.value })} /></div>
      <div className="col-md-4"><label className="tj-label">State</label><input className="form-control tj-input" type="text" placeholder="Auto-filled from map" value={form.state} onChange={e => setForm({ ...form, state: e.target.value })} /></div>
      <div className="col-md-4"><label className="tj-label">Zip Code</label><input className="form-control tj-input" type="text" placeholder="Auto-filled from map" value={form.zipCode} onChange={e => setForm({ ...form, zipCode: e.target.value })} /></div>
      <div className="col-12"><div className="p-3 rounded-3" style={{ background: 'rgba(37,99,235,0.04)', border: '1px solid rgba(37,99,235,0.15)' }}><p className="tj-label mb-3" style={{ color: '#2563eb' }}><FaCalendarAlt className="me-1" /> Job Date &amp; Time Window</p><div className="row g-3"><div className="col-md-6"><label className="tj-label">From (arrive after)</label><input type="datetime-local" className="form-control tj-input" value={form.jobDate?.from || ''} onChange={e => setForm({ ...form, jobDate: { ...form.jobDate, from: e.target.value } })} /></div><div className="col-md-6"><label className="tj-label">To (arrive before)</label><input type="datetime-local" className="form-control tj-input" value={form.jobDate?.to || ''} onChange={e => setForm({ ...form, jobDate: { ...form.jobDate, to: e.target.value } })} /></div></div></div></div>
      <div className="col-12"><label className="tj-label">Description <span className="text-danger">*</span></label><ReactQuill theme="snow" value={form.description} onChange={(html) => setForm({ ...form, description: html })} placeholder="Describe the work required…" modules={{ toolbar: [[{ header: [1,2,3,false] }],['bold','italic','underline','strike'],[{ list: 'ordered' },{ list: 'bullet' }],['link'],['clean']] }} formats={['header','bold','italic','underline','strike','list','bullet','link']} style={{ background: '#fff', borderRadius: 8 }} /><input type="text" required tabIndex={-1} value={form.description.replace(/<[^>]+>/g, '').trim()} onChange={() => {}} style={{ opacity: 0, height: 0, padding: 0, border: 'none', position: 'absolute' }} /></div>
      <div className="col-md-6"><label className="tj-label">Preferred Skills</label><input className="form-control tj-input" value={form.preferredSkills} onChange={(e) => setForm({ ...form, preferredSkills: e.target.value })} placeholder="AC, electrical, repair (comma separated)" /></div>
      <div className="col-md-6"><label className="tj-label">Requirements</label><input className="form-control tj-input" value={form.requirements} onChange={(e) => setForm({ ...form, requirements: e.target.value })} placeholder="Tools, safety gear (comma separated)" /></div>
      <div className="col-12"><TaskBuilder tasks={form.tasks || []} onChange={(tasks) => setForm({ ...form, tasks })} /></div>
      <div className="col-12 d-flex justify-content-end gap-2 pt-2"><button type="button" className="btn tj-btn-ghost" onClick={onCancel} disabled={saving}>Cancel</button><button type="submit" className="btn tj-btn-primary-gold" disabled={saving}>{saving ? <><span className="spinner-border spinner-border-sm me-2" />Saving…</> : isTemplate ? (isEditing ? 'Update Template' : 'Save Template') : isEditing ? 'Update Job' : 'Create Job'}</button></div>
    </form>
  );
};

export default JobForm;
